### ISSUE TITLE
Test Extension in other browser

### ISSUE THREAD

**Issue by pomdtr** [pomdtr/wesh#3]
- [ ] Arc
- [ ] Brave
- [ ] Edge
- [ ] Firefox

**Comment by fzdwx** [comment]
Need firefox

**Comment by pomdtr** [comment]
@raguay turns out arc already works:

![image](https://github.com/pomdtr/popcorn/assets/17577332/5386082b-89d2-4411-99cf-470cb95f3c2a)

**Comment by raguay** [comment]
It will not load for me. It says it can't load the icon file.
